package bitmanipulation;

/**
 * Created by Shikha on 27/04/18.
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindtheDifference {
    public static char findTheDifference(String s, String t) {
        if(s.length()==0 && t.length()==1)
            return t.charAt(0);
        int xor=s.charAt(0);
        for(int i=1;i<s.length();i++){
            xor = xor ^ s.charAt(i);
        }
        for(int i=0;i<t.length();i++){
            xor = xor ^ t.charAt(i);
        }
        return (char)xor;
    }

    public static void  main(String[] args){
        System.out.println(findTheDifference("abcd","acbde"));
    }
}
